import { randomUUID } from "node:crypto";
import type { Server } from "node:http";
import WebSocket, { WebSocketServer } from "ws";
import type { Env } from "../../config/env.js";
import { prisma } from "../../config/database.js";
import { resolveAccessToken } from "../../middleware/security.js";
import { AuthorizedChatContextBuilder } from "./context.js";

export function attachChatWebSocket(server: Server, env: Env) {
  const wss=new WebSocketServer({server,path:"/api/v1/ws/chat",maxPayload:64*1024}); const contexts=new AuthorizedChatContextBuilder();
  wss.on("connection", client=>{let principal:any=null; client.send(JSON.stringify({type:"ready",message:"Authenticate before sending chat messages."})); client.on("message",async raw=>{try{const data=JSON.parse(raw.toString()); if(data.type==="authenticate"){principal=await resolveAccessToken(env.JWT_ACCESS_SECRET,String(data.accessToken||"")); if(!principal.permissions.includes("chat:authorized")||principal.clearanceRank<2)throw new Error("Chat access denied"); client.send(JSON.stringify({type:"authenticated"})); return;} if(!principal){client.send(JSON.stringify({type:"error",code:"AUTHENTICATION_REQUIRED"}));return;} const question=String(data.question||"").trim(); const investigationId=String(data.investigationId||""); if(!question||question.length>4000||!investigationId){client.send(JSON.stringify({type:"error",code:"INVALID_CHAT_MESSAGE"}));return;} const requestId=randomUUID(); const built=await contexts.forInvestigation(investigationId,principal); const upstreamUrl=new URL("/ws/chat",env.RAG_BASE_URL); upstreamUrl.protocol=upstreamUrl.protocol==="https:"?"wss:":"ws:"; if(env.RAG_API_KEY)upstreamUrl.searchParams.set("api_key",env.RAG_API_KEY); const upstream=new WebSocket(upstreamUrl); let answer=""; upstream.on("open",()=>upstream.send(JSON.stringify({message:question,authenticated:true,userId:principal.userId,subjectId:built.subjectId,investigationId,context:built.context}))); upstream.on("message",async message=>{const event=JSON.parse(message.toString()); if(event.type==="token")answer+=String(event.text||""); client.send(JSON.stringify({...event,requestId})); if(event.type==="done"){const conversationId=String(data.conversationId||event.conversationId||randomUUID()); await prisma.ragInteraction.create({data:{conversationId,requestId,userId:principal.userId,scope:"AUTHORIZED",question,answer,sources:event.sources||[],accessScope:{role:principal.role,clearanceRank:principal.clearanceRank},contextManifest:{contractVersion:"prysm-authorized-rag-context-v1",investigationId,subjectId:built.subjectId,transport:"websocket"},ragVersion:"prysm-rag-1.0.0",status:"SUCCEEDED"}}); upstream.close();}}); upstream.on("error",()=>client.send(JSON.stringify({type:"error",code:"RAG_UNAVAILABLE",requestId})));}catch{client.send(JSON.stringify({type:"error",code:"CHAT_REQUEST_FAILED"}));}});});
  return wss;
}
