import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { Prisma, PrismaClient } from "@prisma/client";
const db = new PrismaClient();
const stableUuid = (value: string) => { const b=Buffer.from(createHash("sha256").update(value).digest().subarray(0,16)); b[6]=(b[6]!&0x0f)|0x50; b[8]=(b[8]!&0x3f)|0x80; const h=b.toString("hex"); return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`; };
const json = (x: unknown) => JSON.parse(JSON.stringify(x)) as Prisma.InputJsonValue;
async function main() {
  const path=process.argv[2]; if(!path) throw new Error("Usage: npm run ingest:slice -- <slice.json>"); const input=JSON.parse(await readFile(path,"utf8"));
  const subjectIds=new Map<string,string>(); const graphIds=new Map<string,string>();
  for(const node of input.nodes){ const subjectId=stableUuid(`subject:${node.nodeKey}`); const graphId=stableUuid(`graph-node:${node.nodeKey}`); const displayLabel=node.profile?.fullName||node.nodeKey; await db.subject.upsert({where:{id:subjectId},update:{displayLabel,status:node.status},create:{id:subjectId,subjectType:node.nodeType,externalRef:node.nodeKey,displayLabel,status:node.status,classificationRank:2}}); if(node.profile) await db.subjectProfile.upsert({where:{subjectId},update:{fullName:node.profile.fullName,dateOfBirth:node.profile.dateOfBirth?new Date(node.profile.dateOfBirth):null,countryCode:node.profile.countryCode,riskCategory:node.profile.riskCategory,sensitiveAttributes:node.profile.attributes?json(node.profile.attributes):undefined},create:{subjectId,fullName:node.profile.fullName,dateOfBirth:node.profile.dateOfBirth?new Date(node.profile.dateOfBirth):null,countryCode:node.profile.countryCode,riskCategory:node.profile.riskCategory,sensitiveAttributes:node.profile.attributes?json(node.profile.attributes):undefined}}); await db.graphNode.upsert({where:{id:graphId},update:{subjectId:subjectId,nodeType:node.nodeType,externalKey:node.nodeKey,embedding:node.embedding?json(node.embedding):undefined,embeddingModelVersion:input.embeddingVersion},create:{id:graphId,subjectId,nodeType:node.nodeType,externalKey:node.nodeKey,labelHash:createHash("sha256").update(node.nodeKey).digest("hex"),embedding:node.embedding?json(node.embedding):undefined,embeddingModelVersion:input.embeddingVersion}}); subjectIds.set(node.nodeKey,subjectId); graphIds.set(node.nodeKey,graphId); }
  const snapshotId=stableUuid(`snapshot:${input.graphVersion}:${input.cutoff}:${input.featureVersion}`); await db.gnnGraphSnapshot.upsert({where:{id:snapshotId},update:{nodeCount:BigInt(input.nodes.length),edgeCount:BigInt(input.edges.length),metadata:json({subjects:input.subjects,source:input.artifactRoot,embeddingVersion:input.embeddingVersion})},create:{id:snapshotId,graphVersion:input.graphVersion,cutoffAt:new Date(input.cutoff),nodeCount:BigInt(input.nodes.length),edgeCount:BigInt(input.edges.length),featureSchemaVersion:input.featureVersion,metadata:json({subjects:input.subjects,source:input.artifactRoot,embeddingVersion:input.embeddingVersion})}});
  for(const node of input.nodes){ const graphNodeId=graphIds.get(node.nodeKey)!; await db.gnnNode.upsert({where:{snapshotId_graphNodeId:{snapshotId,graphNodeId}},update:{gnnIndex:BigInt(node.gnnIndex),featureVersion:input.featureVersion},create:{snapshotId,graphNodeId,gnnIndex:BigInt(node.gnnIndex),nodeType:node.nodeType,featureVersion:input.featureVersion}}); if(node.embedding) await db.gnnEmbedding.upsert({where:{snapshotId_graphNodeId_modelVersion:{snapshotId,graphNodeId,modelVersion:input.embeddingVersion}},update:{embedding:json(node.embedding),generatedAt:new Date()},create:{snapshotId,graphNodeId,modelVersion:input.embeddingVersion,embedding:json(node.embedding),generatedAt:new Date(),metadata:json({cutoffSafe:false,usage:"versioned retrospective reference only"})}}); }
  let txCount=0;
  for(const [index,edge] of input.edges.entries()){ const sourceNodeId=graphIds.get(edge.sourceKey); const targetNodeId=graphIds.get(edge.targetKey); if(!sourceNodeId||!targetNodeId) continue; const edgeId=stableUuid(`graph-edge:${edge.edgeId}`); await db.graphEdge.upsert({where:{id:edgeId},update:{},create:{id:edgeId,sourceNodeId,targetNodeId,edgeType:edge.edgeType,weight:edge.confidence,firstSeenAt:edge.eventTime?new Date(edge.eventTime):null,lastSeenAt:edge.eventTime?new Date(edge.eventTime):null,validFrom:edge.eventTime?new Date(edge.eventTime):null,validTo:edge.endTime?new Date(edge.endTime):null,sourceReference:edge.transactionId||edge.relationshipId||edge.edgeId,properties:json({canonicalEdgeId:edge.edgeId,sourceTable:edge.sourceTable})}}); await db.gnnEdge.upsert({where:{snapshotId_graphEdgeId:{snapshotId,graphEdgeId:edgeId}},update:{},create:{snapshotId,graphEdgeId:edgeId,sourceGnnIndex:BigInt(input.nodes.find((n:any)=>n.nodeKey===edge.sourceKey).gnnIndex),targetGnnIndex:BigInt(input.nodes.find((n:any)=>n.nodeKey===edge.targetKey).gnnIndex),edgeType:edge.edgeType}}); if(edge.edgeType==="transfers"&&edge.transactionId&&edge.amountEtb!=null){ const fromAccountId=subjectIds.get(edge.sourceKey); const toAccountId=subjectIds.get(edge.targetKey); await db.transaction.upsert({where:{sourceTransactionId:String(edge.transactionId)},update:{},create:{id:stableUuid(`transaction:${edge.transactionId}`),sourceTransactionId:String(edge.transactionId),fromAccountId,toAccountId,amount:new Prisma.Decimal(edge.amountEtb),currency:String(edge.currency||"ETB").slice(0,3),timestamp:new Date(edge.eventTime),transactionType:"transfer",sourceSystem:"prysm-ai-canonical",rawMetadata:json({canonicalEdgeId:edge.edgeId})}}); txCount++; } }
  console.log(JSON.stringify({status:"ok",subjects:input.nodes.length,graphNodes:input.nodes.length,graphEdges:input.edges.length,transactions:txCount,snapshotId}));
}
main().finally(()=>db.$disconnect());
